### ISSUE TITLE
New user generations use last used model without keywords

### ISSUE THREAD

**Issue by cadaeix** [philpax/exilent#67]
If a new person does a generation and only specifies the prompt, and if the last used model is a model with a keyword, the generation goes ahead but without inserting the keyword

This is inconsistent with how other generations with keyword models work

Two possibilities:

- The generation goes ahead with that model and inserts the keyword
- The generation defaults to a default model (possibly specified in config) which may or may not have a keyword that can be inserted

**Comment by philpax** [comment]
oic, this is because it's relying on the state of the webui, not of Exilent. I suppose I could fetch the current model from the webui and use that, or maybe I should just force people to specify models

**Comment by philpax** [comment]
If they don't have a model specified and one can't be found through the fallback mechanisms of previous generations / presets / etc I'll error out and tell them to pick a model. Dependent on #64.
